name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          
      # Debug outputs
      - name: Debug outputs
        run: |
          echo "release_created: ${{ steps.release.outputs.release_created }}"
          echo "tag_name: ${{ steps.release.outputs.tag_name }}"

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: release-please
    # Remove the condition temporarily to see if builds work
    # if: ${{ needs.release-please.outputs.release_created }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # Start with just Linux for testing

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.17.0
      env:
        CIBW_BUILD: "cp311-*"  # Just Python 3.11 for testing
        CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux_*"
        CIBW_BEFORE_BUILD: "pip install pybind11 numpy cmake"
        CIBW_BEFORE_ALL_LINUX: "yum install -y cmake3 eigen3-devel || (apt-get update && apt-get install -y cmake libeigen3-dev)"

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl